#
# Shiny User interface to the rabies burden model.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#

library(shiny)
library(rhandsontable)

# User interface
shinyUI(fluidPage(
  
  # Application title
  titlePanel("Burden of Rabies"),
  
  # Sidebar with a slider input for number of bins 
  sidebarLayout(
    sidebarPanel(
       h1("Select:"),
       "Choose your country code to get default input values",
       uiOutput("countrySelector"),  # Set dynamically
       actionButton("start", "Calculate"), br(),
       h3("pPEP data", title="Generated by burden_1 - hardcoded for now"),
       tableOutput("pPEP_table")
    ),
    
    # Show a plot of the generated distribution
    mainPanel(
       h2("Output:"),
       h3("Country Data"),
       "Country: ", textOutput("country", inline=TRUE),br(),
       "Continent: ", textOutput("continent", inline=TRUE),br(),
       "Cluster: ", textOutput("cluster", inline=TRUE),br(),
       "Population (2010): ", textOutput("population", inline=TRUE),
       h3("Editable pPEP data"),
       rHandsontableOutput("pPEP_table_editable", width = 350),
       h3("Burden data", title="(this is the burden.csv file)"),
       tableOutput("burden_table")
    )
  )
))
