#
# Shiny User interface to the rabies burden model.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#

library(shiny)
library(rhandsontable)

# User interface
shinyUI(fluidPage(
  
  verticalLayout(
    titlePanel("Estimating the Burden of Rabies"),
    
    sidebarLayout(
      sidebarPanel(
         h3("Select Country to access the default input values:"),
         uiOutput("countrySelector"), br() # Set dynamically
     
    ),
      
    
    mainPanel(
         h3("Country Statistics"),
         "Country: ", textOutput("country", inline=TRUE),br(),
         "Continent: ", textOutput("continent", inline=TRUE),br(),
         "Cluster: ", textOutput("cluster", inline=TRUE),br(),
         "Population (2010): ", textOutput("population", inline=TRUE),br(),
         "HDI:", textOutput("HDI", inline=TRUE)
    )
    ),
    h3("Original Burden model input values", title="Generated by burden_1 - hardcoded for now"),
    DT::dataTableOutput("pPEP_table"),
    
    p("BI = Annual incidence of dog bites"),
    p("RP = Probability that exposure is by a rabid animal"),
    p("PP = Probability of receiving PEP given an exposure"),
    p("l or _L and u or _U refer to lower and upper confidence intervals"), br(),

    
    h3("Editable model input values"),
    rHandsontableOutput("pPEP_table_editable", width = '100%'),
    p("If you edit coverage, it will not affect mRP and the resulting deaths just yet"), 
    p("not sure about how lower and upper confidence intervals used right now"), br(),  
   

    actionButton("start", "Run Burden Model"), br(),
  
  
    h3("Burden model output", title="(this is the burden.csv file)"),
    DT::dataTableOutput("burden_table")
  )
))
