#
# Shiny User interface to the rabies burden model.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#

library(shiny)
library(rhandsontable)

# User interface
shinyUI(fluidPage(
  
  verticalLayout(
    titlePanel("Burden of Rabies"),
    
    sidebarLayout(
      sidebarPanel(
         h1("Select:"),
         "Choose your country code to get default input values",
         uiOutput("countrySelector"),  # Set dynamically
         actionButton("start", "Calculate"), br()
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         h3("Country Data"),
         "Country: ", textOutput("country", inline=TRUE),br(),
         "Continent: ", textOutput("continent", inline=TRUE),br(),
         "Cluster: ", textOutput("cluster", inline=TRUE),br(),
         "Population (2010): ", textOutput("population", inline=TRUE)
      )
    ),
    h3("pPEP data", title="Generated by burden_1 - hardcoded for now"),
    DT::dataTableOutput("pPEP_table"),
    #wellPanel()
    h3("Editable pPEP data"),
    rHandsontableOutput("pPEP_table_editable", width = '100%'),
    h3("Burden data", title="(this is the burden.csv file)"),
    DT::dataTableOutput("burden_table")
  )
))
